### ISSUE TITLE
Sources Re: landsat_thermal

### ISSUE THREAD

**Issue by cwmueller87** [TDahlberg/landsat_thermal#3]
Hi TDahlberg,

I've done quite a bit of research and I've tracked down all of the equations, however, I'm unable to find any verification that it's okay to use the ToA conversion after converting to surface radiance. Most of the papers seem to skip that final conversion. If you have anything that can confirm the use of the equation in this way that would be great! I'll then be able to spend a little time updating the script for Landsat 8 data as well.

Thanks,
Chase

**Comment by TDahlberg** [comment]
Whoah, I must have missed this issue a long time ago, sorry about that. I based the equation on a paper from Yale, specifically because the equation made some more assumptions and I could avoid grabbing site-specific emissivity values. Let me look at the paper and I'll get back to you.

**Comment by TDahlberg** [comment]
Okay, tracked it down. I used the formulas from the Yale Center for Earth Observation, from this document: http://www.yale.edu/ceo/Documentation/Landsat_DN_to_Kelvin.pdf. Step 1 is the DN -> SLR, Step 2 (optional) is SLR -> TOA, Step 3 is SLR/TOA -> LST. There didn't seem to be any issues raised in the paper about doing the atmospheric correction after the DN - > SLR conversion. I hope that helps.
[Landsat_DN_to_Kelvin.pdf](https://github.com/TDahlberg/landsat_thermal/files/28905/Landsat_DN_to_Kelvin.pdf)
